routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();
Route::group(['prefix' => ''], function () {
    Auth::routes();
    Route::get('/', 'IndexController@index')->name('index');
    Route::get('/home', 'User\HomeController@index')->name('home');
//Для отображения категорий и новостей
    Route::get('/category/{slug}', 'IndexController@category')->name('category');
    Route::get('/category/{slug}/{filter?}', 'IndexController@category')->name('filter');



    Route::get('/product/{id?}', 'IndexController@product')->name('product');
//    Route::get('/filter', 'IndexController@filterReset')->name('filterReset');
//    Route::post('/filter', 'IndexController@filter')->name('filter');

});

//Авторизация для админа
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {

    Route::get('/login', 'Auth\MyAuthController@showLogin')->name('adminLogin');
    Route::post('/login', 'Auth\MyAuthController@authenticate');
    Route::post('/logout', 'Auth\MyAuthController@logout')->name('adminLogout');
});

//Посредник father смотрит авторизовался ли админ
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'father'], function () {

    Route::get('/', 'AdminController@store')->name('adminStore');
    //смена пароля
    Route::get('/setting', 'AdminController@index')->name('adminSetting');
    Route::post('/setting', 'AdminController@update')->name('adminSettingUpdate');
    //Товары
    Route::resource('/product', 'ProductController', ['as' => 'admin']);
    Route::get('/product/{name?}', 'ProductController@index', ['as' => 'admin'])->name('adminSearch');
    Route::get('/product/{product}/absent', 'ProductController@absent', ['as' => 'admin'])->name('adminAbsent');
    //Заказы
    Route::resource('/order', 'OrderController', ['as' => 'admin']);
    Route::get('/order/{name?}', 'OrderController@index', ['as' => 'admin'])->name('adminOrderSearch');
    //Новая почта
    Route::resource('newpost', 'NewpostController', ['as' => 'admin', 'only' => ['store']]);
    //Пользователи
    Route::resource('/user', 'UserController', ['as' => 'admin']);
    Route::get('/user/{user?}', 'UserController@index', ['as' => 'admin'])->name('adminUserSearch');
    Route::get('/user/{user}/block', 'UserController@block', ['as' => 'admin'])->name('adminUserBlock');
    //Комментарии
    Route::get('/comment', 'CommentController@index', ['as' => 'admin'])->name('admin.comment.index');
    Route::get('/comment/{id?}', 'CommentController@index', ['as' => 'admin'])->name('adminCommentSearch');
    Route::get('/comment/{comment}/block', 'CommentController@block', ['as' => 'admin'])->name('admin.comment.block');
    Route::get('/comment/{comment}/access', 'CommentController@access', ['as' => 'admin'])->name('admin.comment.access');
});

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.app_admin')

@section('navigation')
    @include('admin.navigation')
@endsection

@section('content')
      
@endsection

resources/views/admin/navigation.blade.php
	<header>
			<div class="container-fluid p-0">
				<div class="row m-0">
					<div class="col-12 p-0">
						<div class="nav_container">
							<div class="logo_container"><img src="{{ asset('images/admin/main_logo_white.svg') }}" alt=""></div>
							<ul class="nav_menu">
								<li class="nav_item">
									<a href="{{ route('admin.product.index') }}">
										<div class="img_container"><img src="{{ asset('images/admin/goods_icon.png') }}" alt=""></div>
										<div class="text"><p>Товары</p></div>
									</a>
								</li>
								<li class="nav_item">
									<a href="{{ route('admin.order.index') }}">
										<div class="img_container"><img src="{{ asset('images/admin/orders_icon.png') }}" alt=""></div>
										<div class="text"><p>Заказы</p></div>
									</a>
								</li>
								<li class="nav_item">
									<a href="{{ route('admin.user.index') }}">
										<div class="img_container"><img src="{{ asset('images/admin/users_icon.png') }}" alt=""></div>
										<div class="text"><p>Пользователи</p></div>
									</a>
								</li>
								<li class="nav_item">
									<a href="{{ route('admin.comment.index') }}">
										<div class="img_container"><img src="{{ asset('images/admin/rating.svg') }}" alt=""></div>
										<div class="text"><p>Отзывы</p></div>
									</a>
								</li>
								<li class="nav_item">
									<a href="{{ route('adminSetting') }}">
										<div class="img_container"><img src="{{ asset('images/admin/settings_icon.png') }}" alt=""></div>
										<div class="text"><p>Настройки</p></div>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</header>

resources/views/admin/setting.blade.php
@extends('admin.layouts.app_admin')

@section('wrap-class')
        <div id="wrapper-settings">
@endsection

@section('navigation')
    @include('admin.navigation')
@endsection

@section('content')

    <main>
        <div class="section_main">
            <div class="container-fluid p-0">
                <div class="row m-0">
                    <div class="col-12 p-0">
                        <div class="header_search">
                            <div class="title">
                                <h1>Настройки</h1>
                            </div>
                            <div class="btn_container">
                                <form id="logout-form" action="{{ route('adminLogout') }}" method="POST">
                                    @csrf
                                    <button type="submit">Выйти</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                @if (\Session::has('error'))
                    <div class="alert alert-danger">
                        <ul>
                            @foreach (\Session::get('error') as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                @if (\Session::has('success'))
                    <div class="alert alert-success">
                        <ul>
                            @foreach (\Session::get('success') as $success)
                                <li>{{$success}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="settings_container">
                    <div class="settings_block row m-0">
                        <div class="col-12 p-0">


                            <form class="settings_form" action="{{route('adminSettingUpdate', $user)}}" method="post">
                                <div class="form_title">
                                    <h1>Изменить пароль</h1>
                                </div>
                                <div class="form_settings_pass">
                                    <div class="row m-0">
                                        <div class="col-4 p-0">
                                            <div class="input_container">
                                                <p class="input_lable">Старый пароль*</p>
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <input type="password" name="current-password">
                                            </div>
                                        </div>
                                        <div class="col-4 p-0">
                                            <div class="input_container">
                                                <p class="input_lable">Новый пароль*</p>
                                                <input type="password" name="password">
                                            </div>
                                        </div>
                                        <div class="col-4 p-0">
                                            <div class="input_container">
                                                <p class="input_lable">Подтверждение*</p>
                                                <input type="password" name="password_confirmation" >
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="btn_container">
                                    <button class="custom_btn save" type="submit">
                                        <span>Сохранить</span>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

@endsection