routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();
Route::group(['prefix' => ''], function () {
    Auth::routes();
    Route::get('/', 'IndexController@index')->name('index');
    Route::get('/home', 'User\HomeController@index')->name('home');
//Для отображения категорий и новостей
    Route::get('/category/{slug}', 'IndexController@category')->name('category');
    Route::get('/category/{slug}/{filter?}', 'IndexController@category')->name('filter');



    Route::get('/product/{id?}', 'IndexController@product')->name('product');
//    Route::get('/filter', 'IndexController@filterReset')->name('filterReset');
//    Route::post('/filter', 'IndexController@filter')->name('filter');

});

//Авторизация для админа
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {

    Route::get('/login', 'Auth\MyAuthController@showLogin')->name('adminLogin');
    Route::post('/login', 'Auth\MyAuthController@authenticate');
    Route::post('/logout', 'Auth\MyAuthController@logout')->name('adminLogout');
});

//Посредник father смотрит авторизовался ли админ
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'father'], function () {

    Route::get('/', 'AdminController@store')->name('adminStore');
    //смена пароля
    Route::get('/setting', 'AdminController@index')->name('adminSetting');
    Route::post('/setting', 'AdminController@update')->name('adminSettingUpdate');
    //Товары
    Route::resource('/product', 'ProductController', ['as' => 'admin']);
    Route::get('/product/{name?}', 'ProductController@index', ['as' => 'admin'])->name('adminSearch');
    Route::get('/product/{product}/absent', 'ProductController@absent', ['as' => 'admin'])->name('adminAbsent');
    //Заказы
    Route::resource('/order', 'OrderController', ['as' => 'admin']);
    Route::get('/order/{name?}', 'OrderController@index', ['as' => 'admin'])->name('adminOrderSearch');
    //Новая почта
    Route::resource('newpost', 'NewpostController', ['as' => 'admin', 'only' => ['store']]);
    //Пользователи
    Route::resource('/user', 'UserController', ['as' => 'admin']);
    Route::get('/user/{user?}', 'UserController@index', ['as' => 'admin'])->name('adminUserSearch');
    Route::get('/user/{user}/block', 'UserController@block', ['as' => 'admin'])->name('adminUserBlock');
    //Комментарии
    Route::get('/comment', 'CommentController@index', ['as' => 'admin'])->name('admin.comment.index');
    Route::get('/comment/{id?}', 'CommentController@index', ['as' => 'admin'])->name('adminCommentSearch');
    Route::get('/comment/{comment}/block', 'CommentController@block', ['as' => 'admin'])->name('admin.comment.block');
    Route::get('/comment/{comment}/access', 'CommentController@access', ['as' => 'admin'])->name('admin.comment.access');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

     //One to One
     public function user_additional(){
        return $this->hasOne('App\UserAdditional');
    }
    //One to Many
     public function comments()
     {
         return $this->hasMany('App\Comment');
     }
      //One to Many
     public function orders()
     {
         return $this->hasMany('App\Order');
     }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\UserAdditional;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //поиск
        if (Input::has('search')) {
           $users =  User::whereHas('user_additional', function ($query) {
                $search = Input::get('search');

                $query->where('firstname', 'like', '%' . $search . '%')->orWhere('lastname', 'like', '%' . $search . '%');
            })->where('name', '<>', 'admin')->orderBy('created_at', 'desc')->paginate(6);
            return view('admin.users.index', [
                'users' => $users
            ]);
        }
        $users =  User::with('user_additional')->where('name', '<>', 'admin')->orderBy('created_at', 'desc')->paginate(6);
        return view('admin.users.index', [
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        $user->user_additional()->delete();
        $user->comments()->delete();

        return redirect()->route('admin.user.index');
    }

    // заблокировать пользователя
    public function block(User $user)
    {
        ($user->status) ? $user->update(['status' => 0]) : $user->update(['status' => 1]);
        return redirect()->back();
    }
}

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.home');
    }
}

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app_admin')


@section('wrap-class')
	<div id="wrapper-users">
@endsection

@section('navigation')
	@include('admin.navigation')
@endsection
 
@section('content')

	<main>
		<div class="section_main">
			<div class="container-fluid p-0">
				<div class="row m-0">
					<div class="col-12 p-0">
						<div class="header_search">
							<div class="title">
								<h1>Пользователи</h1>
							</div>
							<form action="{{ route('adminUserSearch') }}" method="GET">
								<div class="input_container">
									<button type="submit"><img src="{{ asset('images/admin/search_icon.png') }}" alt=""></button>
									<input id="search" type="text" name="search" placeholder="Поиск">
								</div>
							</form>
						</div>
					</div>
				</div>
				<div class="table_main row m-0">
					<div class="col-12 p-0">
						<div class="table_container">
							<table>
								<thead>
								<tr>
									<th>
										<p>Имя</p>
									</th>
									<th>
										<p>Фамилия</p>
									</th>
									<th>
										<p>Телефон</p>
									</th>
									<th>
										<p>Mail</p>
									</th>
									<th>
										<p>Пол</p>
									</th>
									<th>
										<p>Статус</p>
									</th>
									<th>
										<p>Действие</p>
									</th>
								</tr>
								</thead>
								<tbody>
								{{--@forelse($users['data'] as $user)--}}
								{{--<tr>--}}
									{{--<th>--}}
										{{--<p>{{ isset($user['firstname']) ? $user['firstname'] : ''}}</p>--}}
									{{--</th>--}}
									{{--<th>--}}
										{{--<p>{{ isset($user['lastname']) ? $user['lastname'] : '' }}</p>--}}
									{{--</th>--}}
									{{--<th>--}}
										{{--<p>{{ isset($user['phone']) ? $user['phone'] : '' }}</p>--}}
									{{--</th>--}}
									{{--<th>--}}
										{{--<p>{{ isset($user['email']) ? $user['email'] : '' }}</p>--}}
									{{--</th>--}}
									{{--<th>--}}
										{{--<p>{{ isset($user['sex']) ? $user['sex'] : '' }}</p>--}}
									{{--</th>--}}
									{{--<th>--}}
										{{--<p>@if ($user['status']) Активен @else Заблокирован@endif</p>--}}
									{{--</th>--}}
									{{--<th>--}}
										{{--<div class="order_button">--}}
											{{--<img class="btn_show" src="{{ asset('images/admin/button_detailed_icon.png') }}" alt="">--}}
											{{--<div class=" detailed_block">--}}
											{{--<a class="text_btn" href="{{route('adminUserBlock', $user)}}">@if ($user['status']) Заблокировать @else Разблокировать @endif</a>--}}
											{{--<form class="text_btn delete" action="{{route('admin.user.destroy', $user)}}" method="post">--}}
												{{--<input type="hidden" name="_method" value="delete">--}}
												{{--{{ csrf_field() }}--}}
												{{--<button type="submit" class="text_btn" href="{{route('admin.user.destroy', $user)}}">Удалить</button>--}}
											{{--</form>--}}
											{{--</div>--}}
										{{--</div>--}}

									{{--</th>--}}
								{{--</tr>--}}
								{{--@empty--}}
									{{--<tr>--}}
										{{--<td>--}}
											{{--<h3 style="text-alight:center">Данные отсутствуют</h3>--}}
										{{--</td>--}}
									{{--</tr>--}}
								{{--@endforelse--}}
								{{--</tbody>--}}
							{{--</table>--}}
						{{--</div>--}}
					{{--</div>--}}
				{{--</div>--}}
				{{--@php dd($users) @endphp--}}
				{{--@if($users['last_page'] > 1)--}}
					{{--<div class="pagination_container">--}}

						{{--<div class="page_count">--}}
							{{--<p class="page_numb">{{ $users['current_page'] }}</p>--}}
							{{--<span>из</span>--}}
							{{--<p class="page_numb">{{ $users['last_page']}}</p>--}}
						{{--</div>--}}
						{{--<div class="nav_container">--}}
							{{--для отображения стрелочки "Предыдущая страница"--}}
							{{--@if($users['current_page'] !== 1)--}}
								{{--<a href="{{ $users['last_page_url'] }}"><img src="{{ asset('images/admin/arrow_left.png') }}" alt=""></a>--}}
							{{--@endif--}}
							{{--@if($users['current_page'] !== $users['last_page'])--}}
								{{--<a href="{{ $users['next_page_url'] }}"><img src="{{ asset('images/admin/arrow_right.png') }}" alt=""></a>--}}
							{{--@endif--}}
						{{--</div>--}}
					{{--</div>--}}
				{{--@endif--}}
			{{--</div>--}}
		{{--</div>--}}
	{{--</main>--}}


								@forelse($users as $user)
									<tr>
										<th>
											<p>{{ isset($user->user_additional->firstname) ? $user->user_additional->firstname : ''}}</p>
										</th>
										<th>
											<p>{{ isset($user->user_additional->lastname) ? $user->user_additional->lastname : '' }}</p>
										</th>
										<th>
											<p>{{ isset($user->user_additional->phone) ? $user->user_additional->phone : '' }}</p>
										</th>
										<th>
											<p>{{ isset($user->email) ? $user->email : '' }}</p>
										</th>
										<th>
											<p>{{ isset($user->user_additional->sex) ? $user->user_additional->sex : '' }}</p>
										</th>
										<th>
											<p>@if ($user->status) Активен @else Заблокирован@endif</p>
										</th>
										<th>
											<div class="order_button">
												<img class="btn_show" src="{{ asset('images/admin/button_detailed_icon.png') }}" alt="">
												<div class=" detailed_block">
													<a class="text_btn" href="{{route('adminUserBlock', $user)}}">@if ($user->status) Заблокировать @else Разблокировать @endif</a>
													<form class="text_btn delete" action="{{route('admin.user.destroy', $user)}}" method="post">
														<input type="hidden" name="_method" value="delete">
														{{ csrf_field() }}
														<button type="submit" class="text_btn" href="{{route('admin.user.destroy', $user)}}">Удалить</button>
													</form>
												</div>
											</div>

										</th>
									</tr>
								@empty
									<tr>
										<td>
											<h3 style="text-alight:center">Данные отсутствуют</h3>
										</td>
									</tr>
								@endforelse
								</tbody>
							</table>
						</div>
					</div>
				</div>
				@if($users->lastPage() > 1)
					<div class="pagination_container">

						<div class="page_count">
							<p class="page_numb">{{ $users->currentPage() }}</p>
							<span>из</span>
							<p class="page_numb">{{ $users->lastPage() }}</p>
						</div>
						<div class="nav_container">
							{{--для отображения стрелочки "Предыдущая страница"--}}
							@if($users->currentPage() !== 1)
								<a href="{{ $users->url(($users->currentPage() - 1 )) }}"><img src="{{ asset('images/admin/arrow_left.png') }}" alt=""></a>
							@endif
							@if($users->currentPage() !== $users->lastPage())
								<a href="{{ $users->url(($users->currentPage() + 1 )) }}"><img src="{{ asset('images/admin/arrow_right.png') }}" alt=""></a>
							@endif
						</div>
					</div>
				@endif
			</div>
		</div>
	</main>





@endsection