routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();
Route::group(['prefix' => ''], function () {
    Auth::routes();
    Route::get('/', 'IndexController@index')->name('index');
    Route::get('/home', 'User\HomeController@index')->name('home');
//Для отображения категорий и новостей
    Route::get('/category/{slug}', 'IndexController@category')->name('category');
    Route::get('/category/{slug}/{filter?}', 'IndexController@category')->name('filter');



    Route::get('/product/{id?}', 'IndexController@product')->name('product');
//    Route::get('/filter', 'IndexController@filterReset')->name('filterReset');
//    Route::post('/filter', 'IndexController@filter')->name('filter');

});

//Авторизация для админа
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {

    Route::get('/login', 'Auth\MyAuthController@showLogin')->name('adminLogin');
    Route::post('/login', 'Auth\MyAuthController@authenticate');
    Route::post('/logout', 'Auth\MyAuthController@logout')->name('adminLogout');
});

//Посредник father смотрит авторизовался ли админ
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'father'], function () {

    Route::get('/', 'AdminController@store')->name('adminStore');
    //смена пароля
    Route::get('/setting', 'AdminController@index')->name('adminSetting');
    Route::post('/setting', 'AdminController@update')->name('adminSettingUpdate');
    //Товары
    Route::resource('/product', 'ProductController', ['as' => 'admin']);
    Route::get('/product/{name?}', 'ProductController@index', ['as' => 'admin'])->name('adminSearch');
    Route::get('/product/{product}/absent', 'ProductController@absent', ['as' => 'admin'])->name('adminAbsent');
    //Заказы
    Route::resource('/order', 'OrderController', ['as' => 'admin']);
    Route::get('/order/{name?}', 'OrderController@index', ['as' => 'admin'])->name('adminOrderSearch');
    //Новая почта
    Route::resource('newpost', 'NewpostController', ['as' => 'admin', 'only' => ['store']]);
    //Пользователи
    Route::resource('/user', 'UserController', ['as' => 'admin']);
    Route::get('/user/{user?}', 'UserController@index', ['as' => 'admin'])->name('adminUserSearch');
    Route::get('/user/{user}/block', 'UserController@block', ['as' => 'admin'])->name('adminUserBlock');
    //Комментарии
    Route::get('/comment', 'CommentController@index', ['as' => 'admin'])->name('admin.comment.index');
    Route::get('/comment/{id?}', 'CommentController@index', ['as' => 'admin'])->name('adminCommentSearch');
    Route::get('/comment/{comment}/block', 'CommentController@block', ['as' => 'admin'])->name('admin.comment.block');
    Route::get('/comment/{comment}/access', 'CommentController@access', ['as' => 'admin'])->name('admin.comment.access');
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['firstname', 'lastname', 'description', 'email', 'phone', 'sex', 'city', 'delivery', 'address', 'sum', 'state'];
//    //Many to Many
//    public function addoptions(){
//        return $this->belongsToMany('App\Addoption');
//    }

   // One to Many
    public function order_history(){
        return $this->hasMany('App\OrderHistory');
    }


     //One to Many
    public function user() {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Order;
use Illuminate\Support\Facades\Input;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use NovaPoshta\Config;
use NovaPoshta\ApiModels\Address;
use NovaPoshta\MethodParameters\Address_getCities;
use NovaPoshta\MethodParameters\Address_getWarehouses;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;
use Image;
use FFMpeg;
use Illuminate\Support\Facades\Storage;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // //поиск
        if (Input::has('search')) {
            $search = Input::get('search');

            $orders = Order::with('order_history')->where('id', 'like', '%' . $search . '%')->orWhere('lastname', 'like', '%' . $search . '%')->paginate(6);
            return view('admin.orders.index', [
                'orders' => $orders,
            ]);
        }
        $orders = Order::with('order_history')->orderBy('created_at', 'desc')->paginate(6);

        return view('admin.orders.index', [
            'orders' => $orders,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {

        Config::setApiKey('ff43e4d939510bf5d965298a3d75bd12');
        Config::setFormat(Config::FORMAT_JSON);
        Config::setLanguage((Config::LANGUAGE_RU));


        $cities = Address::getCities();
        $list_city = $cities->data;


        $products = $order->order_history()->get();
          //dd($products[0]->id);
        return view('admin.orders.edit', [
            'order' => $order,
            'products' => $products,
            'list_city' => $list_city
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
//        dd($request->id_addoption);
        $data = $request->except(['user_id', 'city', 'sum']);

        $validator = $this->admin_credential_rules($data);
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        } else {


            //переводим код города в название
            $cities = new Address_getCities();
            $cities->setRef($request->city);
            $city = Address::getCities($cities)->data[0]->DescriptionRu;

            $sum = 0;
            //удаление товаров из заказа
            if (isset($request->del_prod)) {
                foreach ($request->del_prod as $key => $item) {
                    //если значение в поле 1, значит товар нужно удалить
                    if ($item) {
                        //удаляем изображение
                        Storage::disk('order')->delete($order->order_history[$key]->image);
                        $order->order_history[$key]->delete($request->id_addition[$key]);
                    }
                    //иначе считаем сумму
                    else $sum += $order->order_history[$key]->price * $order->order_history[$key]->count;
                }
            }
            $order->update($data);
            $order->update(['city' => $city]);
            $order->update(['sum' => $sum]);

            return redirect()->route('admin.order.index');
        }
    }


    public function destroy(Order $order)
    {
        //отсоединяем все связи с опциями
        $order->order_history()->delete();
        $order->delete();

        return redirect()->route('admin.order.index');

    }

    public function admin_credential_rules(array $data)
    {

        $validator = Validator::make($data, [
            'firstname' => "required|string|min:2",
            'lastname' => "required|string|min:2",
            'email' => 'string|email|max:255',
            'phone' => "numeric:min:10",
        ]);

        return $validator;
    }


    public function addImage($image)
    {
        $size_path = Config::get('settings.order_image');
        //если существует это изображение, достаем его
        if (Storage::disk('upload')->exists($image)) {
            Storage::disk('upload')->get($image);
            $str = str_random(8) . '.jpeg';
            // Get the filepath of the request file (.tmp) and append .jpg
            $requestImagePath = $image->getRealPath();
            // Modify the image using intervention
            $interventionImage = Image::make($image)->widen($size_path['width'])->encode('jpeg');
            // Save the intervention image over the request image
            $interventionImage->save($requestImagePath);
            //Send to storage
            Storage::disk('order')->putFileAs('', new File($requestImagePath), $str);

            return $str;
        } else
            return false;
    }

}

resources/views/admin/orders/edit.blade.php
@extends('admin.layouts.app_admin')

@section('wrap-class')
    <div id="wrapper-order-info">
@endsection

@section('navigation')
    @include('admin.navigation')
@endsection

@section('content')
    <main>
        <div class="section_main">
            <div class="container-fluid p-0">
                <div class="row m-0">
                    <div class="col-12 p-0">
                        <div class="header_search">
                            <div class="title"><h1>Заказ №{{ $order->id }}</h1></div>
                        </div>
                    </div>
                </div>
                {{--@if ($errors->any())--}}
                    {{--<div class="alert alert-danger">--}}
                        {{--<ul>--}}
                            {{--@foreach ($errors->all() as $error)--}}
                                {{--<li>{{ $error }}</li>--}}
                            {{--@endforeach--}}
                        {{--</ul>--}}
                    {{--</div>--}}
                {{--@endif--}}
                <div class="order_info_container">
                    <form class="order_form" action="{{route('admin.order.update', $order)}}" method="post">
                        <input type="hidden" name="_method" value="put">
                        {{ csrf_field() }}
                        @include('admin.orders.partials.form')
                    </form>
                </div>
            </div>
        </div>
    </main>
@endsection

resources/views/admin/orders/index.blade.php
@extends('admin.layouts.app_admin')


@section('wrap-class')
	<div id="wrapper-orders">
@endsection

@section('navigation')
	@include('admin.navigation')
@endsection
 
@section('content')

<main>
	<div class="section_main">
		<div class="container-fluid p-0">
			<div class="row m-0">
				<div class="col-12 p-0">
					<div class="header_search">
						<div class="title">
							<h1>Заказы</h1>
						</div>
						<form action="{{ route('adminOrderSearch') }}" method="GET">
							<div class="input_container">
								<button type="submit"><img src="{{ asset('images/admin/search_icon.png') }}" alt=""></button>
								<input id="search" type="text" name="search" placeholder="Поиск">
							</div>
						</form>
					</div>
				</div>
			</div>
			<div class="table_main row m-0">
				<div class="col-12 p-0">
					<div class="table_container">
						<table>
							<thead>
							<tr>
								<th><p>Номер заказа</p></th>
								<th><p>Пользователь</p></th>
								<th><p>Сумма</p></th>
								<th><p>Статус</p></th>
								<th><p>Дата</p></th>
								<th><p>Действие</p></th>
							</tr>
							</thead>
							<tbody>
							@forelse($orders as $order)
							<tr>
								<th><p>{{ $order->id }}</p></th>
								<th><p>{{ $order->firstname  }} {{ $order->lastname }}</p></th>
								<th><p>{{ $order->sum }}</p></th>
								<th><p>{{ $order->state }}</p></th>
								<th><p>{{ $order->created_at->format('d.m.Y') }}</p></th>
								<th>
									<div class="order_button">
										<img class="btn_show" src="{{ asset('images/admin/button_detailed_icon.png') }}" alt="">
										<div class="detailed_block">
											<a class="text_btn" href="{{route('admin.order.edit', $order)}}">Редактировать</a>
											<form class="text_btn delete" action="{{route('admin.order.destroy', $order)}}" method="post">
												<input type="hidden" name="_method" value="delete">
												{{ csrf_field() }}
												<button type="submit" class="text_btn" href="{{route('admin.order.destroy', $order)}}">Удалить</button>
											</form>
										</div>
									</div>
								</th>
							</tr>
							@empty
								<tr>
									<td>
										<h3 style="text-alight:center">Данные отсутствуют</h3>
									</td>
								</tr>
							@endforelse
							</tbody>
						</table>
					</div>
				</div>
			</div>

			@if($orders->lastPage() > 1)
				<div class="pagination_container">

					<div class="page_count">
						<p class="page_numb">{{ $orders->currentPage() }}</p>
						<span>из</span>
						<p class="page_numb">{{ $orders->lastPage() }}</p>
					</div>
					<div class="nav_container">
						{{--для отображения стрелочки "Предыдущая страница"--}}
						@if($orders->currentPage() !== 1)
							<a href="{{ $orders->url(($orders->currentPage() - 1 )) }}"><img src="{{ asset('images/admin/arrow_left.png') }}" alt=""></a>
						@endif
						@if($orders->currentPage() !== $orders->lastPage())
							<a href="{{ $orders->url(($orders->currentPage() + 1 )) }}"><img src="{{ asset('images/admin/arrow_right.png') }}" alt=""></a>
						@endif
					</div>
				</div>
			@endif


		</div>
	</div>
</main>




@endsection