routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();
Route::group(['prefix' => ''], function () {
    Auth::routes();
    Route::get('/', 'IndexController@index')->name('index');
    Route::get('/home', 'User\HomeController@index')->name('home');
//Для отображения категорий и новостей
    Route::get('/category/{slug}', 'IndexController@category')->name('category');
    Route::get('/category/{slug}/{filter?}', 'IndexController@category')->name('filter');



    Route::get('/product/{id?}', 'IndexController@product')->name('product');
//    Route::get('/filter', 'IndexController@filterReset')->name('filterReset');
//    Route::post('/filter', 'IndexController@filter')->name('filter');

});

//Авторизация для админа
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {

    Route::get('/login', 'Auth\MyAuthController@showLogin')->name('adminLogin');
    Route::post('/login', 'Auth\MyAuthController@authenticate');
    Route::post('/logout', 'Auth\MyAuthController@logout')->name('adminLogout');
});

//Посредник father смотрит авторизовался ли админ
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'father'], function () {

    Route::get('/', 'AdminController@store')->name('adminStore');
    //смена пароля
    Route::get('/setting', 'AdminController@index')->name('adminSetting');
    Route::post('/setting', 'AdminController@update')->name('adminSettingUpdate');
    //Товары
    Route::resource('/product', 'ProductController', ['as' => 'admin']);
    Route::get('/product/{name?}', 'ProductController@index', ['as' => 'admin'])->name('adminSearch');
    Route::get('/product/{product}/absent', 'ProductController@absent', ['as' => 'admin'])->name('adminAbsent');
    //Заказы
    Route::resource('/order', 'OrderController', ['as' => 'admin']);
    Route::get('/order/{name?}', 'OrderController@index', ['as' => 'admin'])->name('adminOrderSearch');
    //Новая почта
    Route::resource('newpost', 'NewpostController', ['as' => 'admin', 'only' => ['store']]);
    //Пользователи
    Route::resource('/user', 'UserController', ['as' => 'admin']);
    Route::get('/user/{user?}', 'UserController@index', ['as' => 'admin'])->name('adminUserSearch');
    Route::get('/user/{user}/block', 'UserController@block', ['as' => 'admin'])->name('adminUserBlock');
    //Комментарии
    Route::get('/comment', 'CommentController@index', ['as' => 'admin'])->name('admin.comment.index');
    Route::get('/comment/{id?}', 'CommentController@index', ['as' => 'admin'])->name('adminCommentSearch');
    Route::get('/comment/{comment}/block', 'CommentController@block', ['as' => 'admin'])->name('admin.comment.block');
    Route::get('/comment/{comment}/access', 'CommentController@access', ['as' => 'admin'])->name('admin.comment.access');
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['firstname', 'lastname', 'description', 'email', 'phone', 'sex', 'city', 'delivery', 'address', 'sum', 'state'];
//    //Many to Many
//    public function addoptions(){
//        return $this->belongsToMany('App\Addoption');
//    }

   // One to Many
    public function order_history(){
        return $this->hasMany('App\OrderHistory');
    }


     //One to Many
    public function user() {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Order;
use Illuminate\Support\Facades\Input;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use NovaPoshta\Config;
use NovaPoshta\ApiModels\Address;
use NovaPoshta\MethodParameters\Address_getCities;
use NovaPoshta\MethodParameters\Address_getWarehouses;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;
use Image;
use FFMpeg;
use Illuminate\Support\Facades\Storage;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // //поиск
        if (Input::has('search')) {
            $search = Input::get('search');

            $orders = Order::with('order_history')->where('id', 'like', '%' . $search . '%')->orWhere('lastname', 'like', '%' . $search . '%')->paginate(6);
            return view('admin.orders.index', [
                'orders' => $orders,
            ]);
        }
        $orders = Order::with('order_history')->orderBy('created_at', 'desc')->paginate(6);

        return view('admin.orders.index', [
            'orders' => $orders,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {

        Config::setApiKey('ff43e4d939510bf5d965298a3d75bd12');
        Config::setFormat(Config::FORMAT_JSON);
        Config::setLanguage((Config::LANGUAGE_RU));


        $cities = Address::getCities();
        $list_city = $cities->data;


        $products = $order->order_history()->get();
          //dd($products[0]->id);
        return view('admin.orders.edit', [
            'order' => $order,
            'products' => $products,
            'list_city' => $list_city
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
//        dd($request->id_addoption);
        $data = $request->except(['user_id', 'city', 'sum']);

        $validator = $this->admin_credential_rules($data);
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        } else {


            //переводим код города в название
            $cities = new Address_getCities();
            $cities->setRef($request->city);
            $city = Address::getCities($cities)->data[0]->DescriptionRu;

            $sum = 0;
            //удаление товаров из заказа
            if (isset($request->del_prod)) {
                foreach ($request->del_prod as $key => $item) {
                    //если значение в поле 1, значит товар нужно удалить
                    if ($item) {
                        //удаляем изображение
                        Storage::disk('order')->delete($order->order_history[$key]->image);
                        $order->order_history[$key]->delete($request->id_addition[$key]);
                    }
                    //иначе считаем сумму
                    else $sum += $order->order_history[$key]->price * $order->order_history[$key]->count;
                }
            }
            $order->update($data);
            $order->update(['city' => $city]);
            $order->update(['sum' => $sum]);

            return redirect()->route('admin.order.index');
        }
    }


    public function destroy(Order $order)
    {
        //отсоединяем все связи с опциями
        $order->order_history()->delete();
        $order->delete();

        return redirect()->route('admin.order.index');

    }

    public function admin_credential_rules(array $data)
    {

        $validator = Validator::make($data, [
            'firstname' => "required|string|min:2",
            'lastname' => "required|string|min:2",
            'email' => 'string|email|max:255',
            'phone' => "numeric:min:10",
        ]);

        return $validator;
    }


    public function addImage($image)
    {
        $size_path = Config::get('settings.order_image');
        //если существует это изображение, достаем его
        if (Storage::disk('upload')->exists($image)) {
            Storage::disk('upload')->get($image);
            $str = str_random(8) . '.jpeg';
            // Get the filepath of the request file (.tmp) and append .jpg
            $requestImagePath = $image->getRealPath();
            // Modify the image using intervention
            $interventionImage = Image::make($image)->widen($size_path['width'])->encode('jpeg');
            // Save the intervention image over the request image
            $interventionImage->save($requestImagePath);
            //Send to storage
            Storage::disk('order')->putFileAs('', new File($requestImagePath), $str);

            return $str;
        } else
            return false;
    }

}

resources/views/admin/orders/partials/form.blade.php
<div class="row m-0">
    <div class="order_block col-6 p-0">
        <div class="form_title">
            <h1>Информация о заказе</h1>
            <h2 class="date">{{ $order->created_at->format('d.m.Y') }}</h2>
        </div>
        <div class="form_order_info">
            <div class="row m-0">
                <div class="col-6 p-0">
                    <div class="input_container">
                        <p class="input_lable">Имя</p>
                        <input type="text" class="@if($errors->first('firstname')) error @endif" name="firstname" placeholder="Ваше имя"
                               value="{{ isset($order->firstname) ? $order->firstname : '' }}">
                    </div>
                </div>
                <div class="col-6 p-0">
                    <div class="input_container">
                        <p class="input_lable">Фамилия</p>
                        <input type="text" class="@if($errors->first('lastname')) error @endif" name="lastname" placeholder="Ваша фамилия"
                               value="{{ isset($order->lastname) ? $order->lastname : '' }}">
                    </div>
                </div>
                <div class="col-6 p-0">
                    <div class="input_container">
                        <p class="input_lable">Mail</p>
                        <input type="email" class="@if($errors->first('email')) error @endif" name="email" placeholder="Ваш e-mail"
                               value="{{ isset($order->email) ? $order->email : '' }}">
                    </div>
                </div>
                <div class="col-6 p-0">
                    <div class="input_container">
                        <p class="input_lable">Телефон</p>
                        <input type="text" class="@if($errors->first('phone')) error @endif" name="phone" placeholder="Ваш телефон"
                               value="{{ isset($order->phone) ? $order->phone : '' }}">
                    </div>
                </div>
                <div class="col-6 p-0">
                    <div class="input_container">
                        <p class="input_lable">Пол</p>
                        <div class="styled-select">
                            <select class="styled" name="sex" id="styled">
                                <option value="0" @if ( isset($order->sex) && $order->sex == 0) selected="" @endif>
                                    Мужской
                                </option>
                                <option value="1" @if ( isset($order->sex) && $order->sex == 1) selected="" @endif>
                                    Женский
                                </option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="col-6 p-0">
                    <div class="input_container">
                        <p class="input_lable">Метод доставки</p>
                        <div class="styled-select">
                        <select class="styled" name="delivery" id="styled">
                            <option value="Новая почта" @if ( isset($order->delivery) && $order->delivery == 'Новая почта') selected="" @endif>Новая почта</option>
                            <option value="Курьер" @if ( isset($order->delivery) && $order->delivery == 'Курьер') selected="" @endif>Курьер</option>
                            <option value="Самовывоз" @if ( isset($order->delivery) && $order->delivery == 'Самовывоз') selected="" @endif>Самовывоз</option>
                        </select>
                        </div>
                    </div>

                </div>

                <div class="col-6 p-0">

                    <div class="input_container">
                        <p class="input_lable">Город</p>
                        <div class="styled-select">
                            <select class="styled" name="city" data-order_id="{{ $order->id }}" id="city_id" data-action="{{ route('admin.newpost.store') }}">
                                @foreach($list_city as $city)
                                       <option value="{{ $city->Ref }}" @if ($order->city == $city->DescriptionRu) selected="" @endif>{{ $city->DescriptionRu }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                </div>
                <div class="col-6 p-0">

                    <div class="input_container">
                        <p class="input_lable">Адрес доставки</p>
                        <div class="styled-select">
                            <select class="styled" name="address" id="address_id">
                                @isset ($order->address) <option id="" value="{{ $order->address }}" selected="">{{ $order->address }}</option> @endisset
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-12 p-0">
                    <div class="input_container">
                        <p class="input_lable">Комментарий к доставке</p>
                        <textarea name="description" cols="30" rows="5" placeholder="Ваш комментарий">
                            {{ isset($order->description) ? $order->description : '' }}
                        </textarea>
                    </div>
                </div>
                <div class="col-6 p-0">
                    <div class="input_container">
                        <p class="input_lable">Статус заказа</p>
                        <div class="styled-select">
                            <select class="styled" name="state" id="styled">
                                <option value="Новый" @if ( isset($order->state) && $order->state == 'Новый') selected="" @endif>Новый</option>
                                <option value="Принят в обработку" @if ( isset($order->state) && $order->state == 'Принят в обработку') selected="" @endif>Принят в работу</option>
                                <option value="Оплачен" @if ( isset($order->state) && $order->state == 'Оплачен') selected="" @endif>Оплачен</option>
                                <option value="Отправлен" @if ( isset($order->state) && $order->state == 'Отправлен') selected="" @endif>Отправлен</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="btn_container">
            <button class="custom_btn save" type="submit"><span>Сохранить</span></button>
            <button class="custom_btn"><a href="{{ route('admin.order.index') }}">Отменить</a></button>
        </div>
    </div>

    <div class="order_block col-6 p-0">
        <div class="order_list">
            <div class="form_title">
                <h1>Информация о заказе</h1>
            </div>
            <div class="list_container">

                @foreach ($products as $product)
                    {{--@php $product->product->images = json_decode($product->product->images);--}}
                    {{--@endphp--}}
                    <div class="parent_product_info">
                        <div class="product_info">
                            <div class="product_img_name">
                                <div class="image_container"><img
                                            src="{{ Storage::disk('order')->url($product->image ) }}"
                                            alt=""></div>
                                <div class="product_name"><p><span>{{ $product->name }}</span>, размер
                                        <span>{{ $product->size }}</span>, вес <span>{{ $product->weight }}</span>г.,
                                        к-во <span>{{ $product->count }}</span></p>
                                </div>
                            </div>
                            <div class="product_price">
                                <div class="text"><p><span>{{ $product->price * $product->count }}</span> грн</p></div>
                                {{--<div class="text"><p><span>{{ rtrim($product->price, '0') }}</span> грн</p></div>--}}
                                <div class="btn_container">
                                    <a href="#">Удалить</a>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" class="del_prod" name="del_prod[]" value="">
                        <input type="hidden" name="id_addoption[]" value="{{ $product->id }}">
                    </div>
                @endforeach

            </div>
            <div class="sum_all">
                <div class="text"><p>Общая сумма:</p></div>
                <div class="text"><p class="sum"><span>0</span> грн</p></div>
                <input type="hidden" name="sum" value="">
            </div>
        </div>
    </div>
</div>